module: TPGSwift
author: Yannick Heinrich
author_url: https://blog.yageek.net
copyright: "© 2016 Yannick Heinrich"
skip_undocumented: false
framework_root: Sources
umbrella_header: Sources/TPGSwift.h
